jobs:
  update_repo_info:
    docker:
      - image: devdemisto/dockerbuild:1.0.0.56
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - 14:21:1f:33:1d:a7:6a:e1:b7:c0:a8:83:20:db:e5:5c
      - run:
          name: Update Docker Repo Info
          command: |
            ./update-repository-info.sh
      - store_artifacts:
          path: artifacts
workflows:
  version: 2
  full_build:
    jobs:
      - update_repo_info
  nightly:
    jobs:
      - update_repo_info
    triggers:
      - schedule:
          cron: "0 1 * * *"
          filters:
            branches:
              only:
                - master