jobs:
  update_repo_info:
    docker:
      - image: devdemisto/dockerbuild:1.0.0.56
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker
      # - add_ssh_keys:
      #     fingerprints:
      #       - b1:6a:a6:66:d3:20:c5:eb:0d:00:5a:17:04:3b:89:47
      - run:
          name: Update Docker Repo Info
          command: |
            ./update-repository-info.sh
      - store_artifacts:
          path: artifacts
workflows:
  version: 2
  full_build:
    jobs:
      - update_repo_info
  nightly:
    jobs:
      - update_repo_info
    triggers:
      - schedule:
          cron: "0 1 * * *"
          filters:
            branches:
              only:
                - master