jobs:
  update_repo_info:
    docker:
      - image: devdemisto/dockerbuild:1.0.0.25778
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - SHA256:HDjXb+EIco/xPtCiblLoN2WDyjfRl8488OsY+JW0EoM
      - run:
          name: Update Docker Repo Info
          command: |
            ./update-repository-info.sh
      - store_artifacts:
          path: artifacts
workflows:
  version: 2
  full_build:
    jobs:
      - update_repo_info
  nightly:
    jobs:
      - update_repo_info
    triggers:
      - schedule:
          cron: "0 1 * * *"
          filters:
            branches:
              only:
                - master
