name: demisto/dockerfiles-info/full_build
on:
  push:
    branches:
    - master
jobs:
  update_repo_info:
    runs-on: ubuntu-latest
    container:
      image: devdemisto/dockerbuild:1.0.0.25778
    steps:
    - uses: actions/checkout@v4.1.0
#     # 'setup_remote_docker' was not transformed because there is no suitable equivalent in GitHub Actions
    # Ensure parameter if_key_exists is set correctly
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2.6.1
      with:
        key: "${{ secrets.CIRCLE_CI_SSH_KEY }}"
        name: circle_ci_id_rsa
        known_hosts: "${{ secrets.CIRCLE_CI_KNOWN_HOSTS }}"
        if_key_exists: fail
    - name: Update Docker Repo Info
      run: "./update-repository-info.sh"
    - uses: actions/upload-artifact@v4.1.0
      with:
        path: artifacts
