name: Docker Repository Update

on: push

jobs:
  update_docker_repo_info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set up pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Install dependencies
        run: pipenv install

      - name: Run update-docker-repo-info script
        run: pipenv run ./update-docker-repo-info.py --docker-image demisto/python3

      - name: Configure Git for commit
        run: |
          git config --global user.email "dc-builder@users.noreply.github.com"
          git config --global user.name "dc-builder"

      - name: Check for changes
        id: git_status
        run: |
          git status --short > git_changes.txt
          cat git_changes.txt
          if [ -s git_changes.txt ]; then
            echo "git_changes=true" >> $GITHUB_ENV
          else
            echo "git_changes=false" >> $GITHUB_ENV
          fi

      - name: Upload artifacts (if changes)
        if: env.git_changes == 'true'
        run: |
          mkdir -p artifacts
          cat git_changes.txt | awk '{print $2}' | sed 's:/*$::' | xargs -I {} cp -rf {} artifacts/. || echo "cp failed for some reason. continue..."
        continue-on-error: true

      - name: Commit and push changes
        if: env.git_changes == 'true'
        run: |
          git add .
          git commit -m "$(date): auto repo info update [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Print completion message
        run: echo "Docker repository update complete."
