name: demisto/dockerfiles-info/nightly

on:
  schedule:
    - cron: '0 1 * * *'  # Runs at 01:00 every day

jobs:
  update_repo_info:
    runs-on: ubuntu-latest
    container:
      image: devdemisto/dockerbuild:1.0.0.25778
    steps:
      - uses: actions/checkout@v4.1.0

      # Ensure parameter if_key_exists is set correctly
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2.6.1
        with:
          key: "${{ secrets.CIRCLE_CI_SSH_KEY }}"
          name: circle_ci_id_rsa
          known_hosts: "${{ secrets.CIRCLE_CI_KNOWN_HOSTS }}"
          if_key_exists: fail

      # Add conditional check for the master branch
      - name: Update Docker Repo Info
        if: github.ref == 'refs/heads/master'
        run: "./update-repository-info.sh"

      - uses: actions/upload-artifact@v4.1.0
        with:
          path: artifacts